# Generated by Django 3.2.4 on 2021-06-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abouttitle', models.CharField(max_length=60)),
                ('aboutpara1', models.TextField()),
                ('aboutpara2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landingheading', models.CharField(max_length=100)),
                ('landingtext', models.TextField()),
            ],
        ),
    ]
