# Generated by Django 3.2.4 on 2021-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='aboutimg',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='homelanding',
            name='landingbackground',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='homelanding',
            name='landinglogo',
            field=models.FileField(upload_to='images'),
        ),
    ]
