# Generated by Django 3.2.4 on 2021-06-27 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0002_homeshows'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelanding',
            name='landingbackground',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homelanding',
            name='landinglogo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home'),
            preserve_default=False,
        ),
    ]
