# Generated by Django 3.2.4 on 2021-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0002_auto_20210715_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abouttitle1', models.CharField(max_length=60)),
                ('abouttext1', models.TextField()),
                ('abouttitle2', models.CharField(max_length=60)),
                ('abouttext2', models.TextField()),
                ('abouttitle3', models.CharField(max_length=60)),
                ('abouttext3', models.TextField()),
                ('staffimg', models.FileField(upload_to='media')),
                ('staffname', models.CharField(max_length=60)),
                ('stafftitle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactbuilding', models.CharField(max_length=60)),
                ('contactcountry', models.CharField(max_length=60)),
                ('contactphone', models.CharField(max_length=60)),
                ('contactemail', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimg', models.FileField(upload_to='media')),
                ('eventtxt', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.FileField(upload_to='media')),
                ('blogheading', models.CharField(max_length=60)),
                ('blogtext', models.CharField(max_length=60)),
                ('blogdate', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showimg', models.FileField(upload_to='media')),
                ('showtitle', models.CharField(max_length=60)),
                ('showperiod', models.CharField(max_length=60)),
                ('showtime', models.CharField(max_length=60)),
                ('showabout', models.TextField()),
                ('showurl', models.URLField()),
            ],
        ),
    ]
