# Generated by Django 3.2.4 on 2021-07-15 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0003_about_contact_events_homeblogs_shows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeblogs',
            old_name='blogdate',
            new_name='blogdate1',
        ),
        migrations.RenameField(
            model_name='homeblogs',
            old_name='blogheading',
            new_name='blogdate2',
        ),
        migrations.RenameField(
            model_name='homeblogs',
            old_name='blogtext',
            new_name='blogdate3',
        ),
        migrations.RenameField(
            model_name='homeblogs',
            old_name='blogimg',
            new_name='blogimg1',
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogheading1',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogheading2',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogheading3',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogimg2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogimg3',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogtext1',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogtext2',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeblogs',
            name='blogtext3',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
