# Generated by Django 3.2.4 on 2021-07-15 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0004_auto_20210715_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='showabout',
            new_name='showabout1',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showimg',
            new_name='showimg1',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showperiod',
            new_name='showperiod1',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showtime',
            new_name='showperiod2',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showtitle',
            new_name='showtime1',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showurl',
            new_name='showurl1',
        ),
        migrations.AddField(
            model_name='shows',
            name='showabout2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='showimg2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='showtime2',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='showtitle1',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='showtitle2',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='showurl2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
