# Generated by Django 3.2.4 on 2021-07-15 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0005_auto_20210715_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelanding',
            old_name='landingheading',
            new_name='landingheading1',
        ),
        migrations.RenameField(
            model_name='homelanding',
            old_name='landingtext',
            new_name='landingtext1',
        ),
        migrations.AddField(
            model_name='homelanding',
            name='landingheading2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homelanding',
            name='landingtext2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
