# Generated by Django 3.2.4 on 2021-07-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0007_auto_20210715_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffimg', models.FileField(upload_to='media')),
                ('staffname', models.CharField(max_length=60)),
                ('stafftitle', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='staffimg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staffname',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stafftitle',
        ),
    ]
