# Generated by Django 3.2.4 on 2021-07-15 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0008_auto_20210715_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='abouttext1',
            new_name='abouttexta',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='abouttext2',
            new_name='abouttextb',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='abouttext3',
            new_name='abouttextc',
        ),
        migrations.AddField(
            model_name='about',
            name='abouttextd',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='abouttexte',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='abouttextf',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='abouttextg',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
