# Generated by Django 3.2.4 on 2021-07-16 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonkmusicke', '0010_auto_20210715_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='eventimg',
            new_name='eventimg1',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventtxt',
            new_name='eventtxt1',
        ),
        migrations.AddField(
            model_name='events',
            name='eventimg2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='eventimg3',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='eventtxt2',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='eventtxt3',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
