# Generated by Django 3.1.3 on 2021-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zonkmusic', '0002_auto_20210717_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staffimg2',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffimg3',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffimg4',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffimg5',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffimg6',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffname2',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffname3',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffname4',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffname5',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staffname6',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='stafftitle2',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='stafftitle3',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='stafftitle4',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='stafftitle5',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='stafftitle6',
        ),
        migrations.AlterField(
            model_name='events',
            name='eventimg1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventimg2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventimg3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='aboutimg',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='homeblogs',
            name='blogimg1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='homeblogs',
            name='blogimg2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='homeblogs',
            name='blogimg3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='homelanding',
            name='landingbackground',
            field=models.FileField(upload_to='media/%y'),
        ),
        migrations.AlterField(
            model_name='homelanding',
            name='landinglogo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='showimg2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffimg1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
