# Generated by Django 3.1.3 on 2021-07-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zonkmusic', '0004_auto_20210717_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='eventimg1',
            new_name='eventimg',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventtxt1',
            new_name='eventtxt',
        ),
        migrations.RemoveField(
            model_name='events',
            name='eventimg2',
        ),
        migrations.RemoveField(
            model_name='events',
            name='eventimg3',
        ),
        migrations.RemoveField(
            model_name='events',
            name='eventtxt2',
        ),
        migrations.RemoveField(
            model_name='events',
            name='eventtxt3',
        ),
    ]
