# Generated by Django 3.1.3 on 2021-07-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zonkmusic', '0005_auto_20210717_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='showabout1',
            new_name='showabout',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showimg1',
            new_name='showimg',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showperiod1',
            new_name='showperiod',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showperiod2',
            new_name='showtime',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showtime1',
            new_name='showtitle',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='showurl1',
            new_name='showurl',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showabout2',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showimg2',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showtime2',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showtitle1',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showtitle2',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='showurl2',
        ),
    ]
