# Generated by Django 3.1.3 on 2021-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zonkmusic', '0006_auto_20210717_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlogs1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('blogheading', models.CharField(max_length=60)),
                ('blogtext', models.CharField(max_length=60)),
                ('blogdate', models.CharField(max_length=60)),
                ('blogurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlogs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('blogheading', models.CharField(max_length=60)),
                ('blogtext', models.CharField(max_length=60)),
                ('blogdate', models.CharField(max_length=60)),
                ('blogurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlogs3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('blogheading', models.CharField(max_length=60)),
                ('blogtext', models.CharField(max_length=60)),
                ('blogdate', models.CharField(max_length=60)),
                ('blogurl', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='HomeBlogs',
        ),
    ]
