# Generated by Django 3.1.3 on 2021-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zonkmusic', '0007_auto_20210717_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGenre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('genretext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeGenre2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreimg', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('genretext', models.CharField(max_length=100)),
            ],
        ),
    ]
